name: Demo Hours Workflow

on:
  issue_comment:
    types: [created, edited]

jobs:
  call-log-hours:
    uses: tianlutech/github-hours-bot/.github/workflows/log-hours.yml@main
    with:
      script_version: "latest"
    secrets:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
