name: Validate Issue Format and Post Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  log-hours:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '### LOG')

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --prod

      - name: Build
        run: pnpm run build

      - name: Log Hours
        run: node dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
